version: '3.8'

services:
  # Streamlit Frontend: The UI for medical personnel
  frontend:
    build:
      context: ./cloud_frontend_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      # Central entry point for all API requests
      - BACKEND_URL=http://load-balancer:8080
    depends_on:
      - load-balancer
    networks:
      - glaucoma-net

  # L7 Resource-Aware Load Balancer (Go)
  load-balancer:
    build:
      context: ./load_balancer
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - CPU_BACKEND=http://ai-worker-cpu:8001
      - GPU_BACKEND=http://ai-worker-gpu:8001
      - SIZE_THRESHOLD=2500000
    depends_on:
      - ai-worker-cpu
      - ai-worker-gpu
    networks:
      - glaucoma-net

  # Standard node for smaller fundus images (CPU-based)
  ai-worker-cpu:
    build:
      context: ./cloud_ai_worker
      dockerfile: Dockerfile
    environment:
      - NODE_TYPE=Standard CPU
      - MODEL_DIR=/app/models
    volumes:
      - ./models:/app/models
    networks:
      - glaucoma-net

  # High-performance node for heavy, high-res images (Simulating GPU)
  ai-worker-gpu:
    build:
      context: ./cloud_ai_worker
      dockerfile: Dockerfile
    environment:
      - NODE_TYPE=High-Performance GPU
      - MODEL_DIR=/app/models
    volumes:
      - ./models:/app/models
    networks:
      - glaucoma-net

networks:
  glaucoma-net:
    driver: bridge