apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  hostPath:
    path: /data/models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: glaucoma
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: models-pv
  resources:
    requests:
      storage: 1Gi
